version: '3.8'

services:
  backend:
    build:
      context: ./
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - API_URL=http://backend:8080/  # Update API URL for the frontend to call the backend

networks:
  app-network:
    driver: bridge